# Generated by Django 4.0.3 on 2022-03-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=200)),
                ('btntext', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('skills_list', models.TextField()),
                ('softwares_list', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
