# Generated by Django 4.0.3 on 2022-03-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_path',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/python.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default='images/hero-img.png', upload_to='images/'),
        ),
    ]
